name: Backend CI

on:
    pull_request:
        branches: ["main"]
        paths:
            - "backend/**"

jobs:
    backend-ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
                  cache-dependency-path: "./backend/package-lock.json"

            - name: Install Backend Dependencies
              run: npm ci
              working-directory: ./backend

            - name: Generate Prisma Client
              run: DATABASE_URL="postgresql://mock:mock@localhost:5432/mock" npx prisma generate
              working-directory: ./backend
